publishDate = "2025-12-31 21:28:10"
updateDate = "2025-12-31 21:29:22"
bodyMd5 = "d77ecc5ab6ee12e5516ba1aaa0fac4be4383fcd74d46eaeb9d9962f709760f5c"
title = "生成AI時代のOGP画像生成にはHeadless Browserは不要説"
summary = "ここまでずっとBlog生成ツールの開発日誌ばっかだったけど、いい加減そろそろ普通のことでも描こうかと思って。TL;DRなんだかんだで作るのが大変なOGP画像生成の実装を生成AIにやらせたら案外良い感じ…"

[[toc]]
    level = 2
    text = "TL;DR"
    id = "tl-dr"

[[toc]]
    level = 2
    text = "OGP画像って作るのめんどいよね"
    id = "ogp"

[[toc]]
    level = 2
    text = "OGP画像生成 PaaS とかあったら楽なのにねー"
    id = "ogp-paas"

[[toc]]
    level = 2
    text = "自家用OGP画像生成エンジンを作ってみた"
    id = "ogp"

[[toc]]
    level = 2
    text = "そんな簡単にもいかず。。"
    id = "heading-8ce3c76184241bcd"

[[toc]]
    level = 2
    text = "やれたこと"
    id = "heading-afc495b6d5939266"

[[toc]]
    level = 2
    text = "やれそうなこと"
    id = "heading-9b39f28736ee1a1d"

[[toc]]
    level = 2
    text = "考えてないこと"
    id = "heading-929fef7d5619b96f"

[[toc]]
    level = 2
    text = "まとめ"
    id = "heading-7f7ad40ba94a2507"