publishDate = "2025-01-27 19:10:00"
updateDate = "2025-01-27 19:10:00"
bodyMd5 = "c324d6c56fc2e44894194bd5ec2d5bf029f65a4408d130ccd524d83d529dd6c1"
title = "index.html と rss feed も生成できるようにした"
summary = "一旦エントリーページを生成してトップページとフィード購読もできるようになった風味。ちょっとコード雑すぎるから綺麗にせんとや。。。"

