publishDate = "2025-11-24 20:22:17"
updateDate = "2025-11-24 20:22:17"
bodyMd5 = "e12f7039166a557467993d31b33367d938a9a9a2b52aa274f9d8dd09ace5c191"
title = "設定ファイルやクラス構造を諸々変えたよ"
summary = "meta.tomlの読み込みがおかしいなと思ったらktomlをだいぶ古いの使ってたので0.7.1にアップデート。そして config.toml がだいぶ雑だったので構造化したのであった。。あとは、コー…"

