publishDate = "2025-11-17 21:55:22"
updateDate = "2025-11-17 21:55:22"
bodyMd5 = "4d7bd600f99c3a792ffd70dfb18ada13e0cf4d8d87dcb9238ccdbde88d83cc08"
title = "Pologen で Tailwind CSS & daisy UI を使うようにしたよ！ Template Engine も変えたよ！！"
summary = "JJUG CCC 2025 Fall に行って意識が高まってたので Pologen を色々と更新してたのでした。大きな課題としてはHTML Template を別ファイルにしたかったRSS Feed …"

