publishDate = "2025-01-26 23:00:00"
updateDate = "2025-01-26 23:00:00"
bodyMd5 = "97076218f143f9922e3dd8ca8082c4fb885c5b788bac2bb32ca50b527daac58d"
title = "そろそろ再開します〜"
summary = "前のサーバがめっちゃクラッシュしてずっと放置しすぎてたけど、そろぼち再開しようということでここに再開します。 note とか色々あるんだけど、やっぱエンジニアなら自前で CMS 作るよねー普通は。とい…"

